### ISSUE TITLE
Jest tests for Vue apps don't work with Veaury: test fails when Vue component is wrapped by React component.

### ISSUE THREAD

**Issue by mrjoeman1** [gloriasoft/veaury#144]
Jest test for Vue app fails when a regular Vue component is wrapped by React component:

```html
<template>
    <AnyReactComponent>
        <AnyVueComponent/>
     </AnyReactComponent>
</template>

<script>
import { applyPureReactInVue } from 'veaury';
const AnyReactComponent = applyPureReactInVue(ReactComponent);
</script>
```

It fails only running in Jest tests, it doesn't fail in the application which is running as usual.
Also it seems it fails only when we navigate to such component (`router.push({name: 'Component from the example above'});`), Veaury fails exactly at this moment.

So when Jest test triggers `router.push()` which will navigate to the described component, it fails with error:
```
Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at String.replace (<anonymous>)
    at _querySelectorAll (/Users/serg/storage/repo/test-veaury/node_modules/nwsapi/src/nwsapi.js:1510:9)
    at Object._querySelector [as first] (/Users/serg/storage/repo/test-veaury/node_modules/nwsapi/src/nwsapi.js:1432:14)
    at HTMLDivElementImpl.querySelector (/Users/serg/storage/repo/test-veaury/node_modules/jsdom/lib/jsdom/living/nodes/ParentNode-impl.js:69:44)
    at HTMLDivElement.querySelector (/Users/serg/storage/repo/test-veaury/node_modules/jsdom/lib/jsdom/living/generated/Element.js:1094:58)
    at HTMLDivElement.window.<computed>.<computed> [as querySelector] (/Users/serg/storage/repo/test-veaury/node_modules/veaury/dist/veaury.umd.js:1:16414)
    at HTMLDivElement.window.<computed>.<computed> [as querySelector] (/Users/serg/storage/repo/test-veaury/node_modules/veaury/dist/veaury.umd.js:1:16598)
    ....
```

Reproduction:
https://github.com/mrjoeman1/veaury-jest-issue

**Comment by devilwjp** [comment]
@mrjoeman1 

Replace `applyReactInVue` with `applyPureReactInVue` in the `src/components/carbon/CarbonProvider.vue` file.

**Comment by mrjoeman1** [comment]
@devilwjp It fixes the test, but if i make the component templates a bit more complex (adding more nested components) tests fail with the same error.

**Comment by devilwjp** [comment]
@mrjoeman1 Give me a detailed test case.

**Comment by devilwjp** [comment]
@mrjoeman1 Try veaury@2.4.5

**Comment by mrjoeman1** [comment]
@devilwjp It seems it works now, thank you!
